### ISSUE TITLE
[FEATURE] Upgrade Documentation 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/export-tool-api#18]
Right now documentation is poor ! We need to make a clear doc to start using the API from top to bottom with examples 
There are  some couple of cool options used by other libraries and my fav is https://www.mkdocs.org/ . We can explore more and add the proper documentation

**Comment by jeafreezy** [comment]
Hi @kshitijrajsharma , mkdocs seems cool! More cool is the material theme(https://github.com/squidfunk/mkdocs-material) which is used for FastAPI documentation. Let me know what you think. I would love to work on this. Thanks!

**Comment by kshitijrajsharma** [comment]
Great ! mkdocs material looks even more cool , Sounds good to me you can go ahead and assign issue to yourself @jeafreezy

**Comment by jeafreezy** [comment]
Alright. Will do. Thanks

**Comment by jeafreezy** [comment]
Hi @kshitijrajsharma , I am making some progress with the documentation (see attached GIF).
I want to ask if there is a particular structure that HOT documentation follows e.g: fonts, theme, icons, logo, colors, table or contents etc. If yes, kindly provide some link to learn more about them. Thanks!
![progress](https://user-images.githubusercontent.com/36086324/205342067-5cad1ea3-3c49-4542-9def-08431703206d.gif)

**Comment by kshitijrajsharma** [comment]
Awesome @jeafreezy this looks brilliant , Thank you so much for working on this . Right now we don't have any font / color specification as far as I know , You can be creative , this already looks amazing , we should add detail documentation of api later on to make it complete . Very fine job 👏

**Comment by jeafreezy** [comment]
Alright, thank you. Will proceed and wrap it up.
