### ISSUE TITLE
[FEATURE] Format galaxy api base and start with clean code for export tool API 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/export-tool-api#2]
This issue is to reformat the repo and remove irrelevant endpoints !

**Comment by jeafreezy** [comment]
Hi @kshitijrajsharma , can you maybe highligh the relevant and irrelevant endpoints to remove?

**Comment by kshitijrajsharma** [comment]
Hey @jeafreezy  ! Yes we will only need raw-data/current-snapshot since export tool api is only focused to provide current snapshot of osm ! I am reformatting the repo and then raising couple of issues to work on !

**Comment by jeafreezy** [comment]
Sounds good @kshitijrajsharma , welldone! I think I've gotten a hang of the codebase now, so I'm looking for something to work on, to further solidify the knowledge.

**Comment by kshitijrajsharma** [comment]
What a brilliant news ! @jeafreezy  You can start with testing docker setup once I get PR merged for - #3  I will create one issue for it ! If you wish you can assign it to yourself

**Comment by jeafreezy** [comment]
Awesome! I look forward 😊
