### ISSUE TITLE
[FEATURE] Apply isort on the codebase 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/export-tool-api#20]
TO make clean and understandable code apply isort on the imports

**Comment by jeafreezy** [comment]
This will be great! I'm thinking there can be some sort of formatters e.g Black and then integrate it with isort(https://pycqa.github.io/isort/docs/configuration/black_compatibility.html) to make the codebase clean overall. What do you think?

**Comment by kshitijrajsharma** [comment]
Yes ! I fully agree on this @jeafreezy  I use black on my local code editor , we can replace flake8 validation to black on github workflow too

**Comment by jeafreezy** [comment]
Sounds good!
