### ISSUE TITLE
Include API User guide to docs , : Can be migrated from redoc 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/export-tool-api#38]
>some pages are blank for now, 
Picking up from todo : 
- Add API User guide to the docs we have , we already have redoc for that and acecssible on API_URL/latest/redoc , It would be better if we can integrate or convert those to md / mkdocs format

_Originally posted by @kshitijrajsharma in https://github.com/hotosm/export-tool-api/issues/36#issuecomment-1347686222_

**Comment by jeafreezy** [comment]
Sounds good @kshitijrajsharma . Will explore the possibilities of converting Open API docs to .md
